name: Generate a build and push to another branch

on:
  push:
    branches:
      - master # The branch name where new changes are committed
env:
    CI: false
jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and Push
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: npm install

      - name: Build Project
        run: npm run build # The build command for your project

      - name: Push to Build Branch
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: build # The branch to push the build assets to
          FOLDER: build # The directory where your build assets are generated
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # GitHub will provide this token automatically
          MESSAGE: "Build: ({sha}) {msg}" # Custom commit message for the build branch
